/*
 * FICO® Score
 * <p>FICO® Score<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cdc.apihub.mx.FS.client.model;

/**
* OneOfRequestScoreDGFolio
*/
public interface OneOfRequestScoreDGFolio {

}
