/*
 * FICO® Score
 * <p>FICO® Score<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cdc.apihub.mx.FS.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * RequestScoreDGPersona
 */


public class RequestScoreDGPersona {
  @SerializedName("nombres")
  private String nombres = null;

  @SerializedName("segundoNombre")
  private String segundoNombre = null;

  @SerializedName("apellidoPaterno")
  private String apellidoPaterno = null;

  @SerializedName("apellidoMaterno")
  private String apellidoMaterno = null;

  @SerializedName("apellidoAdicional")
  private String apellidoAdicional = null;

  @SerializedName("fechaNacimiento")
  private String fechaNacimiento = null;

  @SerializedName("RFC")
  private String RFC = null;

  @SerializedName("CURP")
  private String CURP = null;

  @SerializedName("nacionalidad")
  private String nacionalidad = null;

  @SerializedName("residencia")
  private String residencia = null;

  @SerializedName("estadoCivil")
  private String estadoCivil = null;

  @SerializedName("sexo")
  private String sexo = null;

  @SerializedName("claveElectorIFE")
  private String claveElectorIFE = null;

  @SerializedName("numeroDependientes")
  private String numeroDependientes = null;

  @SerializedName("fechaDefuncion")
  private String fechaDefuncion = null;

  @SerializedName("domicilio")
  private Domicilio domicilio = null;

  public RequestScoreDGPersona nombres(String nombres) {
    this.nombres = nombres;
    return this;
  }

   /**
   * Get nombres
   * @return nombres
  **/
  public String getNombres() {
    return nombres;
  }

  public void setNombres(String nombres) {
    this.nombres = nombres;
  }

  public RequestScoreDGPersona segundoNombre(String segundoNombre) {
    this.segundoNombre = segundoNombre;
    return this;
  }

   /**
   * Get segundoNombre
   * @return segundoNombre
  **/
  public String getSegundoNombre() {
    return segundoNombre;
  }

  public void setSegundoNombre(String segundoNombre) {
    this.segundoNombre = segundoNombre;
  }

  public RequestScoreDGPersona apellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
    return this;
  }

   /**
   * Get apellidoPaterno
   * @return apellidoPaterno
  **/
  public String getApellidoPaterno() {
    return apellidoPaterno;
  }

  public void setApellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
  }

  public RequestScoreDGPersona apellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
    return this;
  }

   /**
   * Get apellidoMaterno
   * @return apellidoMaterno
  **/
  public String getApellidoMaterno() {
    return apellidoMaterno;
  }

  public void setApellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
  }

  public RequestScoreDGPersona apellidoAdicional(String apellidoAdicional) {
    this.apellidoAdicional = apellidoAdicional;
    return this;
  }

   /**
   * Get apellidoAdicional
   * @return apellidoAdicional
  **/
  public String getApellidoAdicional() {
    return apellidoAdicional;
  }

  public void setApellidoAdicional(String apellidoAdicional) {
    this.apellidoAdicional = apellidoAdicional;
  }

  public RequestScoreDGPersona fechaNacimiento(String fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
    return this;
  }

   /**
   * Get fechaNacimiento
   * @return fechaNacimiento
  **/
  public String getFechaNacimiento() {
    return fechaNacimiento;
  }

  public void setFechaNacimiento(String fechaNacimiento) {
    this.fechaNacimiento = fechaNacimiento;
  }

  public RequestScoreDGPersona RFC(String RFC) {
    this.RFC = RFC;
    return this;
  }

   /**
   * Get RFC
   * @return RFC
  **/
  public String getRFC() {
    return RFC;
  }

  public void setRFC(String RFC) {
    this.RFC = RFC;
  }

  public RequestScoreDGPersona CURP(String CURP) {
    this.CURP = CURP;
    return this;
  }

   /**
   * Get CURP
   * @return CURP
  **/
  public String getCURP() {
    return CURP;
  }

  public void setCURP(String CURP) {
    this.CURP = CURP;
  }

  public RequestScoreDGPersona nacionalidad(String nacionalidad) {
    this.nacionalidad = nacionalidad;
    return this;
  }

   /**
   * Get nacionalidad
   * @return nacionalidad
  **/
  public String getNacionalidad() {
    return nacionalidad;
  }

  public void setNacionalidad(String nacionalidad) {
    this.nacionalidad = nacionalidad;
  }

  public RequestScoreDGPersona residencia(String residencia) {
    this.residencia = residencia;
    return this;
  }

   /**
   * Get residencia
   * @return residencia
  **/
  public String getResidencia() {
    return residencia;
  }

  public void setResidencia(String residencia) {
    this.residencia = residencia;
  }

  public RequestScoreDGPersona estadoCivil(String estadoCivil) {
    this.estadoCivil = estadoCivil;
    return this;
  }

   /**
   * Get estadoCivil
   * @return estadoCivil
  **/
  public String getEstadoCivil() {
    return estadoCivil;
  }

  public void setEstadoCivil(String estadoCivil) {
    this.estadoCivil = estadoCivil;
  }

  public RequestScoreDGPersona sexo(String sexo) {
    this.sexo = sexo;
    return this;
  }

   /**
   * Get sexo
   * @return sexo
  **/
  public String getSexo() {
    return sexo;
  }

  public void setSexo(String sexo) {
    this.sexo = sexo;
  }

  public RequestScoreDGPersona claveElectorIFE(String claveElectorIFE) {
    this.claveElectorIFE = claveElectorIFE;
    return this;
  }

   /**
   * Get claveElectorIFE
   * @return claveElectorIFE
  **/
  public String getClaveElectorIFE() {
    return claveElectorIFE;
  }

  public void setClaveElectorIFE(String claveElectorIFE) {
    this.claveElectorIFE = claveElectorIFE;
  }

  public RequestScoreDGPersona numeroDependientes(String numeroDependientes) {
    this.numeroDependientes = numeroDependientes;
    return this;
  }

   /**
   * Get numeroDependientes
   * @return numeroDependientes
  **/
  public String getNumeroDependientes() {
    return numeroDependientes;
  }

  public void setNumeroDependientes(String numeroDependientes) {
    this.numeroDependientes = numeroDependientes;
  }

  public RequestScoreDGPersona fechaDefuncion(String fechaDefuncion) {
    this.fechaDefuncion = fechaDefuncion;
    return this;
  }

   /**
   * Get fechaDefuncion
   * @return fechaDefuncion
  **/
  public String getFechaDefuncion() {
    return fechaDefuncion;
  }

  public void setFechaDefuncion(String fechaDefuncion) {
    this.fechaDefuncion = fechaDefuncion;
  }

  public RequestScoreDGPersona domicilio(Domicilio domicilio) {
    this.domicilio = domicilio;
    return this;
  }

   /**
   * Get domicilio
   * @return domicilio
  **/
  public Domicilio getDomicilio() {
    return domicilio;
  }

  public void setDomicilio(Domicilio domicilio) {
    this.domicilio = domicilio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestScoreDGPersona requestScoreDGPersona = (RequestScoreDGPersona) o;
    return Objects.equals(this.nombres, requestScoreDGPersona.nombres) &&
        Objects.equals(this.segundoNombre, requestScoreDGPersona.segundoNombre) &&
        Objects.equals(this.apellidoPaterno, requestScoreDGPersona.apellidoPaterno) &&
        Objects.equals(this.apellidoMaterno, requestScoreDGPersona.apellidoMaterno) &&
        Objects.equals(this.apellidoAdicional, requestScoreDGPersona.apellidoAdicional) &&
        Objects.equals(this.fechaNacimiento, requestScoreDGPersona.fechaNacimiento) &&
        Objects.equals(this.RFC, requestScoreDGPersona.RFC) &&
        Objects.equals(this.CURP, requestScoreDGPersona.CURP) &&
        Objects.equals(this.nacionalidad, requestScoreDGPersona.nacionalidad) &&
        Objects.equals(this.residencia, requestScoreDGPersona.residencia) &&
        Objects.equals(this.estadoCivil, requestScoreDGPersona.estadoCivil) &&
        Objects.equals(this.sexo, requestScoreDGPersona.sexo) &&
        Objects.equals(this.claveElectorIFE, requestScoreDGPersona.claveElectorIFE) &&
        Objects.equals(this.numeroDependientes, requestScoreDGPersona.numeroDependientes) &&
        Objects.equals(this.fechaDefuncion, requestScoreDGPersona.fechaDefuncion) &&
        Objects.equals(this.domicilio, requestScoreDGPersona.domicilio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombres, segundoNombre, apellidoPaterno, apellidoMaterno, apellidoAdicional, fechaNacimiento, RFC, CURP, nacionalidad, residencia, estadoCivil, sexo, claveElectorIFE, numeroDependientes, fechaDefuncion, domicilio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestScoreDGPersona {\n");
    
    sb.append("    nombres: ").append(toIndentedString(nombres)).append("\n");
    sb.append("    segundoNombre: ").append(toIndentedString(segundoNombre)).append("\n");
    sb.append("    apellidoPaterno: ").append(toIndentedString(apellidoPaterno)).append("\n");
    sb.append("    apellidoMaterno: ").append(toIndentedString(apellidoMaterno)).append("\n");
    sb.append("    apellidoAdicional: ").append(toIndentedString(apellidoAdicional)).append("\n");
    sb.append("    fechaNacimiento: ").append(toIndentedString(fechaNacimiento)).append("\n");
    sb.append("    RFC: ").append(toIndentedString(RFC)).append("\n");
    sb.append("    CURP: ").append(toIndentedString(CURP)).append("\n");
    sb.append("    nacionalidad: ").append(toIndentedString(nacionalidad)).append("\n");
    sb.append("    residencia: ").append(toIndentedString(residencia)).append("\n");
    sb.append("    estadoCivil: ").append(toIndentedString(estadoCivil)).append("\n");
    sb.append("    sexo: ").append(toIndentedString(sexo)).append("\n");
    sb.append("    claveElectorIFE: ").append(toIndentedString(claveElectorIFE)).append("\n");
    sb.append("    numeroDependientes: ").append(toIndentedString(numeroDependientes)).append("\n");
    sb.append("    fechaDefuncion: ").append(toIndentedString(fechaDefuncion)).append("\n");
    sb.append("    domicilio: ").append(toIndentedString(domicilio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
