/*
 * FICO® Score
 * <p>FICO® Score<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cdc.apihub.mx.FS.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * Cuerpo de la petición para obtener respuesta del servicio
 */

public class RequestScoreFolio {
  @SerializedName("folioConsulta")
  private String folioConsulta = null;

  @SerializedName("folioOtorgante")
  private String folioOtorgante = null;

  public RequestScoreFolio folioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
    return this;
  }

   /**
   * Get folioConsulta
   * @return folioConsulta
  **/
  public String getFolioConsulta() {
    return folioConsulta;
  }

  public void setFolioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
  }

  public RequestScoreFolio folioOtorgante(String folioOtorgante) {
    this.folioOtorgante = folioOtorgante;
    return this;
  }

   /**
   * Get folioOtorgante
   * @return folioOtorgante
  **/
  public String getFolioOtorgante() {
    return folioOtorgante;
  }

  public void setFolioOtorgante(String folioOtorgante) {
    this.folioOtorgante = folioOtorgante;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestScoreFolio requestScoreFolio = (RequestScoreFolio) o;
    return Objects.equals(this.folioConsulta, requestScoreFolio.folioConsulta) &&
        Objects.equals(this.folioOtorgante, requestScoreFolio.folioOtorgante);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folioConsulta, folioOtorgante);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestScoreFolio {\n");
    
    sb.append("    folioConsulta: ").append(toIndentedString(folioConsulta)).append("\n");
    sb.append("    folioOtorgante: ").append(toIndentedString(folioOtorgante)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
