/*
 * FICO® Score
 * <p>FICO® Score<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cdc.apihub.mx.FS.client.model;

import com.google.gson.annotations.SerializedName;


import java.util.Objects;

/**
 * Cuerpo de la petición para obtener respuesta del servicio
 */

public class RequestScoreDG {
  @SerializedName("folio")
  private OneOfRequestScoreDGFolio folio = null;

  @SerializedName("persona")
  private RequestScoreDGPersona persona = null;

  public RequestScoreDG folio(OneOfRequestScoreDGFolio folio) {
    this.folio = folio;
    return this;
  }

   /**
   * Get folio
   * @return folio
  **/
  public OneOfRequestScoreDGFolio getFolio() {
    return folio;
  }

  public void setFolio(OneOfRequestScoreDGFolio folio) {
    this.folio = folio;
  }

  public RequestScoreDG persona(RequestScoreDGPersona persona) {
    this.persona = persona;
    return this;
  }

   /**
   * Get persona
   * @return persona
  **/
  public RequestScoreDGPersona getPersona() {
    return persona;
  }

  public void setPersona(RequestScoreDGPersona persona) {
    this.persona = persona;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestScoreDG requestScoreDG = (RequestScoreDG) o;
    return Objects.equals(this.folio, requestScoreDG.folio) &&
        Objects.equals(this.persona, requestScoreDG.persona);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folio, persona);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestScoreDG {\n");
    
    sb.append("    folio: ").append(toIndentedString(folio)).append("\n");
    sb.append("    persona: ").append(toIndentedString(persona)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
