/*
 * FICO® Score
 * <p>FICO® Score<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cdc.apihub.mx.FS.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * Si existen información se entregara en esta estructura de datos.
 */

public class ResponseScore {
  @SerializedName("folio")
  private String folio = null;

  @SerializedName("folioConsulta")
  private String folioConsulta = null;

  @SerializedName("score")
  private ResponseScoreScore score = null;

  public ResponseScore folio(String folio) {
    this.folio = folio;
    return this;
  }

   /**
   * Get folio
   * @return folio
  **/
  public String getFolio() {
    return folio;
  }

  public void setFolio(String folio) {
    this.folio = folio;
  }

  public ResponseScore folioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
    return this;
  }

   /**
   * Get folioConsulta
   * @return folioConsulta
  **/
  public String getFolioConsulta() {
    return folioConsulta;
  }

  public void setFolioConsulta(String folioConsulta) {
    this.folioConsulta = folioConsulta;
  }

  public ResponseScore score(ResponseScoreScore score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  public ResponseScoreScore getScore() {
    return score;
  }

  public void setScore(ResponseScoreScore score) {
    this.score = score;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseScore responseScore = (ResponseScore) o;
    return Objects.equals(this.folio, responseScore.folio) &&
        Objects.equals(this.folioConsulta, responseScore.folioConsulta) &&
        Objects.equals(this.score, responseScore.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(folio, folioConsulta, score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseScore {\n");
    
    sb.append("    folio: ").append(toIndentedString(folio)).append("\n");
    sb.append("    folioConsulta: ").append(toIndentedString(folioConsulta)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
