/*
 * FICO® Score
 * <p>FICO® Score<br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.cdc.apihub.mx.FS.client.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * ResponseScoreScore
 */


public class ResponseScoreScore {
  @SerializedName("nombreScore")
  private String nombreScore = null;

  @SerializedName("valor")
  private Integer valor = null;

  @SerializedName("razones")
  private List<String> razones = null;

  public ResponseScoreScore nombreScore(String nombreScore) {
    this.nombreScore = nombreScore;
    return this;
  }

   /**
   * Get nombreScore
   * @return nombreScore
  **/
  public String getNombreScore() {
    return nombreScore;
  }

  public void setNombreScore(String nombreScore) {
    this.nombreScore = nombreScore;
  }

  public ResponseScoreScore valor(Integer valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Get valor
   * @return valor
  **/
  public Integer getValor() {
    return valor;
  }

  public void setValor(Integer valor) {
    this.valor = valor;
  }

  public ResponseScoreScore razones(List<String> razones) {
    this.razones = razones;
    return this;
  }

  public ResponseScoreScore addRazonesItem(String razonesItem) {
    if (this.razones == null) {
      this.razones = new ArrayList<String>();
    }
    this.razones.add(razonesItem);
    return this;
  }

   /**
   * Get razones
   * @return razones
  **/
  public List<String> getRazones() {
    return razones;
  }

  public void setRazones(List<String> razones) {
    this.razones = razones;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseScoreScore responseScoreScore = (ResponseScoreScore) o;
    return Objects.equals(this.nombreScore, responseScoreScore.nombreScore) &&
        Objects.equals(this.valor, responseScoreScore.valor) &&
        Objects.equals(this.razones, responseScoreScore.razones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nombreScore, valor, razones);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseScoreScore {\n");
    
    sb.append("    nombreScore: ").append(toIndentedString(nombreScore)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    razones: ").append(toIndentedString(razones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
